/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrifingRouteImport } from './routes/brifing'
import { Route as LentaRouteImport } from './routes/lenta'
import { Route as ObHavoRouteImport } from './routes/ob-havo'
import { Route as QidiruvRouteImport } from './routes/qidiruv'
import { Route as SaqlanganRouteImport } from './routes/saqlangan'
import { Route as TahririyatRouteImport } from './routes/tahririyat'
import { Route as ViloyatlarRouteImport } from './routes/viloyatlar'
import { Route as BolimIdRouteImport } from './routes/bolim.$id'
import { Route as MaqolaSlugRouteImport } from './routes/maqola.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrifingRoute = BrifingRouteImport.update({
  id: '/brifing',
  path: '/brifing',
  getParentRoute: () => rootRouteImport,
} as any)
const LentaRoute = LentaRouteImport.update({
  id: '/lenta',
  path: '/lenta',
  getParentRoute: () => rootRouteImport,
} as any)
const ObHavoRoute = ObHavoRouteImport.update({
  id: '/ob-havo',
  path: '/ob-havo',
  getParentRoute: () => rootRouteImport,
} as any)
const QidiruvRoute = QidiruvRouteImport.update({
  id: '/qidiruv',
  path: '/qidiruv',
  getParentRoute: () => rootRouteImport,
} as any)
const SaqlanganRoute = SaqlanganRouteImport.update({
  id: '/saqlangan',
  path: '/saqlangan',
  getParentRoute: () => rootRouteImport,
} as any)
const TahririyatRoute = TahririyatRouteImport.update({
  id: '/tahririyat',
  path: '/tahririyat',
  getParentRoute: () => rootRouteImport,
} as any)
const ViloyatlarRoute = ViloyatlarRouteImport.update({
  id: '/viloyatlar',
  path: '/viloyatlar',
  getParentRoute: () => rootRouteImport,
} as any)
const BolimIdRoute = BolimIdRouteImport.update({
  id: '/bolim/$id',
  path: '/bolim/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MaqolaSlugRoute = MaqolaSlugRouteImport.update({
  id: '/maqola/$slug',
  path: '/maqola/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brifing': typeof BrifingRoute
  '/lenta': typeof LentaRoute
  '/ob-havo': typeof ObHavoRoute
  '/qidiruv': typeof QidiruvRoute
  '/saqlangan': typeof SaqlanganRoute
  '/tahririyat': typeof TahririyatRoute
  '/viloyatlar': typeof ViloyatlarRoute
  '/bolim/$id': typeof BolimIdRoute
  '/maqola/$slug': typeof MaqolaSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brifing': typeof BrifingRoute
  '/lenta': typeof LentaRoute
  '/ob-havo': typeof ObHavoRoute
  '/qidiruv': typeof QidiruvRoute
  '/saqlangan': typeof SaqlanganRoute
  '/tahririyat': typeof TahririyatRoute
  '/viloyatlar': typeof ViloyatlarRoute
  '/bolim/$id': typeof BolimIdRoute
  '/maqola/$slug': typeof MaqolaSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brifing': typeof BrifingRoute
  '/lenta': typeof LentaRoute
  '/ob-havo': typeof ObHavoRoute
  '/qidiruv': typeof QidiruvRoute
  '/saqlangan': typeof SaqlanganRoute
  '/tahririyat': typeof TahririyatRoute
  '/viloyatlar': typeof ViloyatlarRoute
  '/bolim/$id': typeof BolimIdRoute
  '/maqola/$slug': typeof MaqolaSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brifing'
    | '/lenta'
    | '/ob-havo'
    | '/qidiruv'
    | '/saqlangan'
    | '/tahririyat'
    | '/viloyatlar'
    | '/bolim/$id'
    | '/maqola/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brifing'
    | '/lenta'
    | '/ob-havo'
    | '/qidiruv'
    | '/saqlangan'
    | '/tahririyat'
    | '/viloyatlar'
    | '/bolim/$id'
    | '/maqola/$slug'
  id:
    | '__root__'
    | '/'
    | '/brifing'
    | '/lenta'
    | '/ob-havo'
    | '/qidiruv'
    | '/saqlangan'
    | '/tahririyat'
    | '/viloyatlar'
    | '/bolim/$id'
    | '/maqola/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrifingRoute: typeof BrifingRoute
  LentaRoute: typeof LentaRoute
  ObHavoRoute: typeof ObHavoRoute
  QidiruvRoute: typeof QidiruvRoute
  SaqlanganRoute: typeof SaqlanganRoute
  TahririyatRoute: typeof TahririyatRoute
  ViloyatlarRoute: typeof ViloyatlarRoute
  BolimIdRoute: typeof BolimIdRoute
  MaqolaSlugRoute: typeof MaqolaSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brifing': {
      id: '/brifing'
      path: '/brifing'
      fullPath: '/brifing'
      preLoaderRoute: typeof BrifingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lenta': {
      id: '/lenta'
      path: '/lenta'
      fullPath: '/lenta'
      preLoaderRoute: typeof LentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ob-havo': {
      id: '/ob-havo'
      path: '/ob-havo'
      fullPath: '/ob-havo'
      preLoaderRoute: typeof ObHavoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qidiruv': {
      id: '/qidiruv'
      path: '/qidiruv'
      fullPath: '/qidiruv'
      preLoaderRoute: typeof QidiruvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saqlangan': {
      id: '/saqlangan'
      path: '/saqlangan'
      fullPath: '/saqlangan'
      preLoaderRoute: typeof SaqlanganRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tahririyat': {
      id: '/tahririyat'
      path: '/tahririyat'
      fullPath: '/tahririyat'
      preLoaderRoute: typeof TahririyatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viloyatlar': {
      id: '/viloyatlar'
      path: '/viloyatlar'
      fullPath: '/viloyatlar'
      preLoaderRoute: typeof ViloyatlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bolim/$id': {
      id: '/bolim/$id'
      path: '/bolim/$id'
      fullPath: '/bolim/$id'
      preLoaderRoute: typeof BolimIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maqola/$slug': {
      id: '/maqola/$slug'
      path: '/maqola/$slug'
      fullPath: '/maqola/$slug'
      preLoaderRoute: typeof MaqolaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrifingRoute: BrifingRoute,
  LentaRoute: LentaRoute,
  ObHavoRoute: ObHavoRoute,
  QidiruvRoute: QidiruvRoute,
  SaqlanganRoute: SaqlanganRoute,
  TahririyatRoute: TahririyatRoute,
  ViloyatlarRoute: ViloyatlarRoute,
  BolimIdRoute: BolimIdRoute,
  MaqolaSlugRoute: MaqolaSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
